
////////
// Fetch Ingredients 
// [  zig zag ] 


//Input: Labels
messagePriceHighAlert  = ""
messagePriceLowAlert  = ""


//Inpu
//Input: Moving Average
fastPeriodLen = 10
slowPeriodLen = 32
fastPeriod = input(title="Fast Period", group="ZigZag Moving Average", type=input.integer, defval=fastPeriodLen, minval=2, maxval=100, inline="MA")
slowPeriod = input(title="Slow Period", group="ZigZag Moving Average", type=input.integer, defval=slowPeriodLen, minval=2, maxval=100, tooltip = "Number of periods to calculte the fast and slow EMA.", inline="MA")

//Input: Zig-Zag
zigperiod = fastPeriod
upcolor = color.green
downcolor = color.red
txtcol = color.white
zigstyle = "Solid"
zigwidth = 3
len = 5
src = close
var dir1 = 0
var max_array_size = 20
var ziggyzags = array.new_float(0)
messageLabelHigh = messagePriceHighAlert
messageLabelLow = messagePriceLowAlert

//////// 
// Bake
// [

//Function: Truncate
truncate(number, decimals) =>
    factor = pow(10, decimals)
    int(number * factor) / factor

//Function: Percent    
percent(n1, n2) =>
    ((n1 - n2) / n2) * 100
    
//Function: Zig-Zag
add_to_zigzag(pointer, value, bindex)=>
    array.unshift(pointer, bindex)
    array.unshift(pointer, value)
    if array.size(pointer) > max_array_size
        array.pop(pointer)
        array.pop(pointer)
    
update_zigzag(pointer, value, bindex, dir)=>
    if array.size(pointer) == 0
        add_to_zigzag(pointer, value, bindex)
    else
        if (dir == 1 and value > array.get(pointer, 0)) or (dir == -1 and value < array.get(pointer, 0))
            array.set(pointer, 0, value)
            array.set(pointer, 1, bindex)
        0.

//Logic: Zig-Zag
out= ema(src, len)
float highs = highestbars(high, zigperiod) == 0 ? high : na
float lows = lowestbars(low, zigperiod) == 0 ? low : na
dir1 := iff(highs and na(lows), 1, iff(lows and na(highs), -1, dir1))
dir1changed = change(dir1)
if highs or lows
    if dir1changed 
        add_to_zigzag(ziggyzags, dir1 == 1 ? highs : lows, bar_index)
    else
        update_zigzag(ziggyzags, dir1 == 1 ? highs : lows, bar_index, dir1)

if array.size(ziggyzags) >= 6
    var line zzline1 = na
    var label zzlabel1 = na
    var label zzlabelcur = na
    float val = array.get(ziggyzags, 0)
    int point = round(array.get(ziggyzags, 1))
    plabel = ""
    labelcol = downcolor
    if change(val) or change(point)
        float val1 = array.get(ziggyzags, 2)
        int point1 = round(array.get(ziggyzags, 3))
        pr = dir1 == 1 ? tostring(high) : tostring(low)
        plabel := dir1 == 1 ? tostring(high,"#.##") : tostring(low,"#.##")
        plabel += "\n" + tostring(truncate(int(percent(val,val1)), 2)) + "%"

        labelcol := dir1 == 1 ? array.get(ziggyzags, 0) > out ? upcolor : downcolor : array.get(ziggyzags, 0) < out ? downcolor : upcolor

        if change(val1) == 0 and change(point1) == 0
            line.delete(zzline1)
            label.delete(zzlabel1)

        if (false)
            zzline1 := line.new(x1 = point, x2 = point1, y1 = val, y2 = val1, color = dir1 == 1 ? upcolor : downcolor, width = zigwidth, style = zigstyle == "Solid" ? line.style_solid : line.style_dotted)
    
        if (showLables)
            zzlabel1 := label.new(x = point, y = val, text = plabel, color = labelcol, textcolor = txtcol, style = dir1 == 1 ? label.style_label_down : label.style_label_up) 
            
    pROCLevel = roc(close, fastPeriod)
    rocLevels = 0.0
    for n = 0 to fastPeriod-1
        rocLevels += roc(close[n], fastPeriod)
    maROCLevel = rocLevels/fastPeriod
    pivotLevel = percent(close,val)

    plabel := tostring(truncate(pivotLevel, 2)) + "%"
    //plabel += "\n"
    //plabel += "\nRoC: " + tostring(pROCLevel, "#.##") + "%"


    labelcol := dir1 == 1 ? array.get(ziggyzags, 0) > out ? upcolor : downcolor : array.get(ziggyzags, 0) < out ? downcolor : upcolor
        
    if (showLables)
        if zzlabelcur == na
            zzlabelcur := label.new(bar_index+1, close, text = plabel, textcolor = color.white, style = label.style_label_left, color = close > open ? color.green : color.red)
        label.set_xy(zzlabelcur,bar_index+1, close)
        label.set_color(zzlabelcur,close > open ? color.green : color.red)
        label.set_text(zzlabelcur,plabel)
   